name: pomodoro_mpv_demo
description: Pomodoro MVVM demo (no Firebase)
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  http: ^0.13.6
  fl_chart: ^0.68.0
  intl: ^0.18.0
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/tomato.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tomato.png" 
  min_sdk_android: 21

flutter_native_splash:
  color: "#DFF8C8"
  image: assets/tomato.png
  android: true
  ios: true
